var bcrypt = require('bcrypt-nodejs');
var crypto = require('crypto');
var mongoose = require('mongoose');

var productSchema = new mongoose.Schema({
    name: String,
    borrower: String, //THIS SHOULD BE THE _ID GENERATED BY MONGO
    lender: String, //THIS SHOULD BE THE _ID GENERATED BY MONGO 
    description: String,
    productid_id: Number,
    imgUrl: String,
    price: Number,
    isBorrowed: Boolean
});


module.exports = mongoose.model('Product', productSchema);
